const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const characters = [
    {
      name: "Sophia",
      age: 25,
      nationality: "American",
      hairColor: "Brown",
      eyeColor: "Hazel",
      hobbies: "Painting, yoga, coffee tasting",
      bio: "25-year-old artist from Brooklyn with a passion for creativity.",
      avatarUrl: "/images/Sophia.jpg",
      loraToken: "sophia-style",
    },
    {
      name: "Maya",
      age: 28,
      nationality: "Canadian",
      hairColor: "Black",
      eyeColor: "Brown",
      hobbies: "Traveling, photography, hiking",
      bio: "Travel blogger who loves exploring cultures and capturing moments.",
      avatarUrl: "/images/Maya.jpg",
      loraToken: "maya-style",
    },
    {
      name: "Lila",
      age: 23,
      nationality: "German",
      hairColor: "Blonde",
      eyeColor: "Blue",
      hobbies: "Gaming, coding, sci-fi movies",
      bio: "Tech enthusiast and gamer from Berlin with a love for sci-fi.",
      avatarUrl: "/images/Lila.jpg",
      loraToken: "lila-style",
    },
    {
      name: "Aria",
      age: 27,
      nationality: "Italian",
      hairColor: "Dark Brown",
      eyeColor: "Green",
      hobbies: "Cooking, fashion design, opera",
      bio: "Italian chef in Milan who blends tradition with modern style.",
      avatarUrl: "/images/Aria.jpg",
      loraToken: "aria-style",
    },
    {
      name: "Hana",
      age: 24,
      nationality: "Japanese",
      hairColor: "Black",
      eyeColor: "Brown",
      hobbies: "Tea ceremony, calligraphy, anime",
      bio: "Traditional meets modern — an anime fan and tea expert in Kyoto.",
      avatarUrl: "/images/Hana.jpg",
      loraToken: "hana-style",
    },
    {
      name: "Camila",
      age: 26,
      nationality: "Brazilian",
      hairColor: "Brown",
      eyeColor: "Brown",
      hobbies: "Dancing, beach volleyball, music festivals",
      bio: "Brazilian dancer who brings sunshine and rhythm everywhere she goes.",
      avatarUrl: "/images/Camila.jpg",
      loraToken: "camila-style",
    },
    {
      name: "Zara",
      age: 30,
      nationality: "Moroccan",
      hairColor: "Black",
      eyeColor: "Hazel",
      hobbies: "Architecture, poetry, desert hikes",
      bio: "Architect from Marrakesh inspired by Moroccan culture and design.",
      avatarUrl: "/images/Zara.jpg",
      loraToken: "zara-style",
    },
    {
      name: "Elena",
      age: 29,
      nationality: "Russian",
      hairColor: "Blonde",
      eyeColor: "Blue",
      hobbies: "Ballet, ice skating, literature",
      bio: "Elegant ballet dancer with a love for Russian literature.",
      avatarUrl: "/images/Elena.jpg",
      loraToken: "elena-style",
    },
    {
      name: "Aisha",
      age: 22,
      nationality: "Nigerian",
      hairColor: "Black",
      eyeColor: "Brown",
      hobbies: "Afrobeats, painting, soccer",
      bio: "Energetic and artistic, she lives for rhythm and color.",
      avatarUrl: "/images/Aisha.jpg",
      loraToken: "aisha-style",
    },
    {
      name: "Isabella",
      age: 31,
      nationality: "Spanish",
      hairColor: "Brown",
      eyeColor: "Green",
      hobbies: "Flamenco, wine tasting, art museums",
      bio: "Loves to dance flamenco and share her vibrant Spanish culture.",
      avatarUrl: "/images/Isabella.jpg",
      loraToken: "isabella-style",
    },
    {
      name: "Nora",
      age: 27,
      nationality: "Swedish",
      hairColor: "Blonde",
      eyeColor: "Blue",
      hobbies: "Skiing, design, fika",
      bio: "Minimalist designer from Stockholm with a love for Nordic winters.",
      avatarUrl: "/images/Nora.jpg",
      loraToken: "nora-style",
    },
    {
      name: "Amara",
      age: 24,
      nationality: "Indian",
      hairColor: "Black",
      eyeColor: "Brown",
      hobbies: "Bollywood dance, cooking, cricket",
      bio: "Loves Bollywood energy and brings joy to every gathering.",
      avatarUrl: "/images/Amara.jpg",
      loraToken: "amara-style",
    },
    {
      name: "Chloe",
      age: 26,
      nationality: "French",
      hairColor: "Brown",
      eyeColor: "Hazel",
      hobbies: "Fashion, cinema, patisserie",
      bio: "Parisian fashion lover who indulges in cinema and croissants.",
      avatarUrl: "/images/Chloe.jpg",
      loraToken: "chloe-style",
    },
    {
      name: "Layla",
      age: 28,
      nationality: "Egyptian",
      hairColor: "Black",
      eyeColor: "Brown",
      hobbies: "History, belly dancing, desert adventures",
      bio: "Historian at heart, she loves the mystery of ancient Egypt.",
      avatarUrl: "/images/Layla.jpg",
      loraToken: "layla-style",
    },
    {
      name: "Valentina",
      age: 25,
      nationality: "Argentinian",
      hairColor: "Dark Brown",
      eyeColor: "Green",
      hobbies: "Tango, football, photography",
      bio: "Energetic and passionate, she embodies the spirit of Buenos Aires.",
      avatarUrl: "/images/Valentina.jpg",
      loraToken: "valentina-style",
    },
  ];

  for (const char of characters) {
    await prisma.character.upsert({
      where: { name: char.name },
      update: char,
      create: char,
    });
  }
}

main()
  .then(() => console.log("✅ 15 Characters Seeded!"))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
