export const metadata = {
  title: "Terms of Service | E-Dating",
};

export default function TermsPage() {
  return (
    <div className="prose prose-invert max-w-3xl mx-auto p-6">
      <h1>Terms of Service</h1>
      <p><strong>Effective Date:</strong> September 2025</p>

      <h2>1. Eligibility</h2>
      <p>You must be at least 18 years old to use this Service. By using the Service, you represent that you are legally able to enter into this agreement.</p>

      <h2>2. Use of the Service</h2>
      <ul>
        <li>No spamming, botting, or attempting to overload the system.</li>
        <li>No abusive, harassing, or illegal behavior.</li>
        <li>No attempts to reverse engineer or exploit the Service.</li>
      </ul>
      <p>We reserve the right to suspend or terminate your account at any time.</p>

      <h2>3. Accounts</h2>
      <p>You are responsible for all activity under your account. We may suspend or ban accounts at our discretion.</p>

      <h2>4. Payments</h2>
      <p>Payments are processed by third-party providers (e.g., Stripe). All sales are final unless otherwise stated. Pricing may change at any time.</p>

      <h2>5. AI Content Disclaimer</h2>
      <p>Chat responses are generated by AI and may be inaccurate or inappropriate. We do not guarantee accuracy, reliability, or safety of AI content. Use at your own risk.</p>

      <h2>6. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, we are not liable for damages arising out of your use of the Service, AI content, or user conduct.</p>

      <h2>7. Changes to Terms</h2>
      <p>We may update these Terms at any time. Continued use of the Service constitutes acceptance.</p>

      <h2>8. Contact</h2>
      <p>If you have questions, contact us at <a href="mikeb6672@yahoo.com">youremail@example.com</a>.</p>
    </div>
  );
}
